### ISSUE TITLE
Doesn't work with A-Frame 0.4.x

### ISSUE THREAD

**Issue by Sebkasanzew** [xirvr/aframe-gltf#11]
I'm getting an error in [line 189 of aframe-gltf.js](https://github.com/xirvr/aframe-gltf/blob/master/dist/aframe-gltf.js#L189) with the description:

> Uncaught TypeError: Cannot read property 'updateMatrixWorld' of undefined

Any idea how to solve this?

**Comment by msj121** [comment]
I do have this gltf loader and aframe 0.4.0 working together. Perhaps try 0.4.0.

I will also mention that models are extremely hard to load without issue (I have been trying to beat this for a while), so there might be an issue with the expectation of some of the model data. It might be useful to share the model file and or the full console error message.

**Comment by Sebkasanzew** [comment]
I tried it now with the current master build of aframe 0.4.0 with gltf-model support build in.
This solved the issue for me.
