### ISSUE TITLE
Play/Pause

### ISSUE THREAD

**Issue by msj121** [xirvr/aframe-gltf#3]
Is there a way to call play or pause on the component?

**Comment by xirvr** [comment]
No, just auto play and loop:

https://github.com/xirvr/aframe-gltf/blob/master/demo/index.html#L21
https://github.com/xirvr/aframe-gltf/blob/master/src/component.ts#L37

Play and stop are supported in the glTF component this component wraps, though:

https://github.com/KhronosGroup/glTF/blob/master/loaders/threejs/glTFAnimation.js#L62

However, to add in those kinds of controls, I think it would require digging into the new (r73?'ish) animation system and possibly modifying the glTF loader component from ThreeJS to support it.

**Comment by donmccurdy** [comment]
> However, to add in those kinds of controls, I think it would require digging into the new (r73?'ish) animation system and possibly modifying the glTF loader component from ThreeJS to support it.

Done: https://github.com/mrdoob/three.js/pull/10276.

**Comment by xirvr** [comment]
This component has moved to the primary repo: https://github.com/aframevr/aframe/blob/master/docs/components/gltf-model.md
