### ISSUE TITLE
Doesn't work with A-Frame 0.3.x

### ISSUE THREAD

**Issue by RSpace** [xirvr/aframe-gltf#4]
Steps to reproduce: Change the aframe script in `/demo/index.html` to 

```
<script src="https://aframe.io/releases/0.2.0/aframe.js"></script>
```

Nothing appears to be rendered. Due to difference in ThreeJS version? (0.74 vs. 0.76)

**Comment by xirvr** [comment]
Actually this component should be switched over to the new glTF loader, which I assume will be in the next ThreeJS version: https://richtr.github.io/three.js/examples/webgl_loader_gltf.html -- I just haven't had time to test it out yet.

**Comment by RSpace** [comment]
Does it work now? :)

**Comment by xirvr** [comment]
Yep, sorry there was a duplicate and just forgot to close this one.

It needs to be updated to interact with the Animation Mixer, but as it is now it should work.
