### ISSUE TITLE
Renders very weirdly with default A-Frame camera

### ISSUE THREAD

**Issue by RSpace** [xirvr/aframe-gltf#5]
Steps to reproduce:

Remove this line:

```
<a-camera id="camera" fov="20" near="0.1" wasd-controls-enabled="false"></a-camera>
```

from `/demo/index.html`. This will make A-Frame bring in the default camera.

Observe weird stuff in your browser:

![screen shot 2016-10-08 at 18 25 12](https://cloud.githubusercontent.com/assets/5872/19214446/9878a73e-8d84-11e6-8cc9-4843deb933f5.png)

**Comment by RSpace** [comment]
However, if I change the camera line to

```
<a-camera id="camera" look-controls-enabled="true" wasd-controls-enabled="true"></a-camera>
```

it seems it renders correctly. A lot of animated shapes speeding around in the horizon?

**Comment by xirvr** [comment]
This component has moved to the primary repo: https://github.com/aframevr/aframe/blob/master/docs/components/gltf-model.md
