### ISSUE TITLE
Downloads model asset twice

### ISSUE THREAD

**Issue by RSpace** [xirvr/aframe-gltf#6]
In the default demo, the "model.gltf" file is downloaded twice: Once by threejs, and once by aframe.

![image](https://cloud.githubusercontent.com/assets/5872/19214459/ee3bb3dc-8d84-11e6-9eba-85a57586bc72.png)

**Comment by xirvr** [comment]
This component has moved to the primary repo: https://github.com/aframevr/aframe/blob/master/docs/components/gltf-model.md
