### ISSUE TITLE
Update to GLTFLoader v2

### ISSUE THREAD

**Issue by donmccurdy** [xirvr/aframe-gltf#8]
THREE.GLTFLoader has gotten a full rewrite, and the old loader is now moved to a 'examples/js/loaders/deprecated/' folder. New code is [here](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/GLTFLoader.js).

**Comment by xirvr** [comment]
Yep, I have it on my project to-do list to try out the new glTF loader.

If anyone is interested in converting this over to the new loader... shouldn't be too difficult.

**Comment by donmccurdy** [comment]
Great! Looks like it hasn't been around long enough to be in a THREE.js release cut, after that sounds good.

**Comment by donmccurdy** [comment]
Aaaand it just landed in r82.

**Comment by xirvr** [comment]
Aaaaand done.  https://github.com/xirvr/aframe-gltf/releases/tag/1.1

**Comment by donmccurdy** [comment]
Awesome! 🎊 🎊 🎊
