### ISSUE TITLE
Update GLTFLoader for updated animation system

### ISSUE THREAD

**Issue by donmccurdy** [xirvr/aframe-gltf#9]
GLTFLoader.Animation has been removed; the loader now uses THREE.AnimationMixer.

https://github.com/mrdoob/three.js/pull/10276

Hoping to have time to take a look myself, but it may be a week or two, so if someone else wants to pick it up please do!

**Comment by donmccurdy** [comment]
I added an [animation-mixer](https://github.com/donmccurdy/aframe-extras/blob/master/src/loaders/animation-mixer.js) component to aframe-extras (it's also published [standalone on NPM](https://www.npmjs.com/package/aframe-extras.animation-mixer)), which can manage animations for both THREE.js JSON and glTF models, so it should be possible to remove most animation logic from `gltf-model`.

**Comment by xirvr** [comment]
How do you see the relationship between the two working?  I.E. if you have a glTF model tag, and want to auto play animations, how would that ideally work?  Is that already figured out on the Collada (etc) tags?

**Comment by donmccurdy** [comment]
I'm up for suggestions, but the syntax I have in `three-model` and `fbx-model` is this:

```html
<!-- #1 – No animation. -->
<a-entity foo-model="..."></a-entity>

<!-- #2 – Autoplay first animation. -->
<a-entity foo-model="..." animation-mixer></a-entity>

<!-- #3 – Autoplay specific animation. -->
<a-entity foo-model="..." animation-mixer="clip: run"></a-entity>
```

There should probably be an `animation-mixer:"autoplay: false"` option, in case you want to have the `animation-mixer` component but start/stop it programmatically. I haven't added that yet.

THREE.ColladaLoader doesn't yet support the new animation system, so `animation-mixer` isn't compatible with `collada-model`. I'd expect that when THREE.ColladaLoader2 becomes the default eventually, it will support THREE.AnimationMixer.

**Comment by donmccurdy** [comment]
And, the animations array is exposed as `model.animations` or `model.geometry.animations` because that's what both loaders give me.

**Comment by donmccurdy** [comment]
[Here's what the update might involve](https://github.com/donmccurdy/aframe-gltf/compare/feat-npm-only...donmccurdy:feat-three-r83?diff=unified&name=feat-three-r83&w=1), pending #10.

There are a couple issues though:

1. THREE.AnimationMixer currently breaks on tracks containing "." characters in track names, as those are also delimiters (see: https://github.com/mrdoob/three.js/issues/10366). VC.glTF unfortunately falls into this category. 
2. My `animation-mixer` component doesn't yet support multiple concurrent animations. I'll definitely want to add that though, and I think it's beneficial to do things like crossfading animations through a format-agnostic component, rather than in each `foo-model` implementation.

Pending at least (2) and possibly (1), we may want to hold off on merging this.

**Comment by xirvr** [comment]
This component has moved to the primary repo: https://github.com/aframevr/aframe/blob/master/docs/components/gltf-model.md
